"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BackroadNodeManager = void 0;
const tslib_1 = require("tslib");
// eslint-disable-next-line @nx/enforce-module-boundaries
const path_1 = tslib_1.__importDefault(require("path"));
const fs_1 = tslib_1.__importDefault(require("fs"));
const core_1 = require("@backroad/core");
const lodash_1 = require("lodash");
const superjson_1 = tslib_1.__importDefault(require("superjson"));
const object_hasher_1 = require("./object-hasher");
const mime_types_1 = tslib_1.__importDefault(require("mime-types"));
/**
 * Manages the addition of nodes to the tree and also returns vaulues where applicable
 */
class BackroadNodeManager {
    container;
    backroadSession;
    constructor(container, backroadSession) {
        this.container = container;
        this.backroadSession = backroadSession;
    }
    reset(container) {
        this.container = container;
        this.backroadSession.renderQueue.addToQueue(this.#getRenderPayload(container, this.backroadSession));
    }
    getAutoGeneratedId(props, type) {
        const autoGeneratedIdInputs = {
            ...(0, lodash_1.omit)(props, ['id', 'defaultValue']),
            type,
        };
        return object_hasher_1.ObjectHasher.hash(autoGeneratedIdInputs);
    }
    #constructContainerObject(props, type) {
        const nodePath = this.#getDescendantKey();
        const containerNode = {
            path: nodePath,
            args: props,
            type: type,
        };
        return containerNode;
    }
    #addContainerDescendant(containerNodeData) {
        const containerNode = {
            ...containerNodeData,
            path: this.#getDescendantKey(),
            children: [],
        };
        this.container.children.push(containerNode);
        this.backroadSession.renderQueue.addToQueue(this.#getRenderPayload(containerNode, this.backroadSession));
        return new BackroadNodeManager(containerNode, this.backroadSession);
    }
    getOrDefault(id, defaultValue) {
        this.backroadSession.setValueIfNotSet(id, defaultValue);
        return JSON.parse(JSON.stringify(this.backroadSession.valueOf(id)));
    }
    setValue(id, value) {
        this.backroadSession.setValue(id, value);
    }
    // you should not have to call this manually
    // use initialiseAndAddComponentDescendant instead (exception: fileupload)
    #addComponentDescendant(nodeData) {
        const castedNodeData = nodeData;
        this.container.children.push(castedNodeData);
        this.backroadSession.renderQueue.addToQueue(this.#getRenderPayload(castedNodeData, this.backroadSession));
        return this.backroadSession.valueOf(nodeData.id);
    }
    // you should not have to call this manually
    // use initialiseAndAddComponentDescendant instead (exception: fileupload)
    #initialiseAndConstructComponentObject(props, type) {
        const nodePath = this.#getDescendantKey();
        const componentId = props.id || this.getAutoGeneratedId(props, type);
        this.backroadSession.setValueIfNotSet(componentId, 'defaultValue' in props
            ? props.defaultValue
            : typeof core_1.defaultValueFallbacks[type] === 'function'
                ? core_1.defaultValueFallbacks[type]({ args: props })
                : type in core_1.defaultValueFallbacks
                    ? core_1.defaultValueFallbacks[type]
                    : null);
        const componentNode = {
            id: componentId,
            path: nodePath,
            args: (0, lodash_1.omit)(props, [
                'id',
                'type',
                'defaultValue',
            ]),
            type: type,
        };
        return componentNode;
    }
    #initialiseAndAddComponentDescendant(props, type) {
        return this.#addComponentDescendant(this.#initialiseAndConstructComponentObject(props, type));
    }
    #getRenderPayload(node, session) {
        if ('id' in node) {
            return superjson_1.default.stringify({ ...node, value: session.valueOf(node.id) });
        }
        return superjson_1.default.stringify(node);
    }
    #getDescendantKey() {
        return `${this.container.path ? this.container.path + '.' : ''}children.${this.container.children.length}`;
    }
    sidebar(props) {
        return this.#addContainerDescendant(this.#constructContainerObject(props, 'sidebar'));
    }
    base(props) {
        return this.#addContainerDescendant(this.#constructContainerObject(props, 'base'));
    }
    page(props) {
        return this.backroadSession.rootNodeManager.#addContainerDescendant(this.#constructContainerObject(props, 'page'));
    }
    columns(props) {
        const columnsContainer = this.#addContainerDescendant(this.#constructContainerObject(props, 'columns'));
        return (typeof props.columns === 'number'
            ? [...Array(props.columns)]
            : props.columns).map(() => columnsContainer.#addContainerDescendant({ type: 'base', args: {} }));
    }
    collapse(props) {
        return this.#addContainerDescendant(this.#constructContainerObject(props, 'collapse'));
    }
    tabs(props) {
        const tabsContainer = this.#addContainerDescendant(this.#constructContainerObject(props, 'tabs'));
        return [...Array(props.labels.length)].map(() => tabsContainer.#addContainerDescendant({ type: 'base', args: {} }));
    }
    chatMessage(props) {
        return this.#addContainerDescendant(this.#constructContainerObject(props, 'chat_message'));
    }
    link(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'link');
    }
    linkGroup(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'link_group');
    }
    stats(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'stats');
    }
    multiselect(props) {
        const val = this.#initialiseAndAddComponentDescendant(props, 'multiselect');
        return val;
    }
    json(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'json');
    }
    title(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'title');
    }
    button(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'button');
    }
    numberInput(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'number_input');
    }
    write(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'markdown');
    }
    line(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'line_chart');
    }
    select(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'select');
    }
    image(props) {
        const { src, ...restOfArgs } = props;
        let finalSrc = src;
        if (src && !src.startsWith('http')) {
            const localPath = path_1.default.join(process.cwd(), src);
            if (fs_1.default.existsSync(localPath)) {
                // convert to base 64 url string
                finalSrc =
                    `data:${mime_types_1.default.lookup(localPath)};base64,` +
                        fs_1.default.readFileSync(localPath, { encoding: 'base64' });
            }
        }
        return this.#initialiseAndAddComponentDescendant({ ...restOfArgs, src: finalSrc }, 'image');
    }
    table(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'table');
    }
    bar(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'bar_chart');
    }
    pie(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'pie_chart');
    }
    doughnut(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'doughnut_chart');
    }
    radar(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'radar_chart');
    }
    scatter(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'scatter_chart');
    }
    chatInput(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'chat_input');
    }
    colorPicker(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'color_picker');
    }
    checkbox(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'checkbox');
    }
    toggle(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'toggle');
    }
    radio(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'radio');
    }
    textInput(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'text_input');
    }
    fileUpload(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'file_upload');
    }
    video(props) {
        return this.#initialiseAndAddComponentDescendant(props, 'video');
    }
}
exports.BackroadNodeManager = BackroadNodeManager;
//# sourceMappingURL=backroad.js.map