import { type BackroadComponent, type BackroadContainer, type InbuiltComponentTypes, type InbuiltContainerTypes } from '@backroad/core';
import { BackroadSession } from '../server/sessions/session';
type BackroadComponentFormat<ComponentType extends InbuiltComponentTypes> = {
    id?: BackroadComponent<ComponentType, false>['id'];
} & BackroadComponent<ComponentType, false>['args'];
type BackroadContainerFormat<ContainerType extends InbuiltContainerTypes> = BackroadContainer<ContainerType, false>['args'];
/**
 * Manages the addition of nodes to the tree and also returns vaulues where applicable
 */
export declare class BackroadNodeManager<ContainerType extends InbuiltContainerTypes = 'page'> {
    #private;
    container: BackroadContainer<ContainerType, false>;
    private backroadSession;
    constructor(container: BackroadContainer<ContainerType, false>, backroadSession: BackroadSession);
    reset(container: BackroadContainer<ContainerType, false>): void;
    private getAutoGeneratedId;
    getOrDefault<T>(id: string, defaultValue: T): T;
    setValue(id: string, value: any): void;
    sidebar(props: BackroadContainerFormat<'sidebar'>): BackroadNodeManager<"sidebar">;
    base(props: BackroadContainerFormat<'base'>): BackroadNodeManager<"base">;
    page(props: BackroadContainerFormat<'page'>): BackroadNodeManager<"page">;
    columns(props: BackroadContainerFormat<'columns'>): BackroadNodeManager<"base">[];
    collapse(props: BackroadContainerFormat<'collapse'>): BackroadNodeManager<"collapse">;
    tabs(props: BackroadContainerFormat<'tabs'>): BackroadNodeManager<"base">[];
    chatMessage(props: BackroadContainerFormat<'chat_message'>): BackroadNodeManager<"chat_message">;
    link(props: BackroadComponentFormat<'link'>): null;
    linkGroup(props: BackroadComponentFormat<'link_group'>): null;
    stats(props: BackroadComponentFormat<'stats'>): null;
    multiselect(props: BackroadComponentFormat<'multiselect'>): any[];
    json(props: BackroadComponentFormat<'json'>): null;
    title(props: BackroadComponentFormat<'title'>): null;
    button(props: BackroadComponentFormat<'button'>): boolean;
    numberInput(props: BackroadComponentFormat<'number_input'>): number;
    write(props: BackroadComponentFormat<'markdown'>): null;
    line(props: BackroadComponentFormat<'line_chart'>): null;
    select(props: BackroadComponentFormat<'select'>): any;
    image(props: BackroadComponentFormat<'image'>): null;
    table(props: BackroadComponentFormat<'table'>): null;
    bar(props: BackroadComponentFormat<'bar_chart'>): null;
    pie(props: BackroadComponentFormat<'pie_chart'>): null;
    doughnut(props: BackroadComponentFormat<'doughnut_chart'>): null;
    radar(props: BackroadComponentFormat<'radar_chart'>): null;
    scatter(props: BackroadComponentFormat<'scatter_chart'>): null;
    chatInput(props: BackroadComponentFormat<'chat_input'>): string | null;
    colorPicker(props: BackroadComponentFormat<'color_picker'>): string;
    checkbox(props: BackroadComponentFormat<'checkbox'>): boolean;
    toggle(props: BackroadComponentFormat<'toggle'>): boolean;
    radio(props: BackroadComponentFormat<'radio'>): string;
    textInput(props: BackroadComponentFormat<'text_input'>): string;
    fileUpload(props: BackroadComponentFormat<'file_upload'>): import("formidable").File[];
    video(props: BackroadComponentFormat<'video'>): null;
}
export {};
